"""
SQLAlchemy models for the Pine Script DSL engine.

Tables:
  scripts            – user-authored scripts
  script_versions    – version history for each script
  strategy_runs      – execution run log
  signal_history     – per-bar signals generated by runs
  backtest_results   – aggregated backtest statistics
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger, Boolean, Column, DateTime, Float, ForeignKey,
    Index, Integer, JSON, String, Text, UniqueConstraint,
)
from sqlalchemy.orm import relationship

from app.db.database import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


# ─────────────────────────── scripts ─────────────────────────────────────────

class Script(Base):
    __tablename__ = "scripts"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    name        = Column(String(255), nullable=False, default="Untitled Script")
    description = Column(Text, nullable=True)
    source      = Column(Text, nullable=False)
    language    = Column(String(32), nullable=False, default="pine_v1")
    is_active   = Column(Boolean, nullable=False, default=True)
    is_public   = Column(Boolean, nullable=False, default=False)
    user_id     = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)

    # Metadata extracted at validation time
    strategy_name     = Column(String(255), nullable=True)
    indicators_used   = Column(JSON, nullable=True, default=list)  # list[str]
    overlay           = Column(Boolean, nullable=False, default=True)

    created_at  = Column(DateTime(timezone=True), nullable=False, default=_now)
    updated_at  = Column(DateTime(timezone=True), nullable=False, default=_now, onupdate=_now)

    versions    = relationship("ScriptVersion", back_populates="script",
                               cascade="all, delete-orphan", lazy="select")
    runs        = relationship("StrategyRun", back_populates="script",
                               cascade="all, delete-orphan", lazy="select")

    __table_args__ = (
        Index("ix_scripts_created_at", "created_at"),
        Index("ix_scripts_is_active", "is_active"),
    )


# ─────────────────────────── script_versions ─────────────────────────────────

class ScriptVersion(Base):
    __tablename__ = "script_versions"

    id         = Column(Integer, primary_key=True, autoincrement=True)
    script_id  = Column(Integer, ForeignKey("scripts.id", ondelete="CASCADE"),
                        nullable=False)
    version    = Column(Integer, nullable=False, default=1)
    source     = Column(Text, nullable=False)
    note       = Column(String(512), nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, default=_now)

    script     = relationship("Script", back_populates="versions")

    __table_args__ = (
        UniqueConstraint("script_id", "version", name="uq_script_version"),
        Index("ix_script_versions_script_id", "script_id"),
    )


# ─────────────────────────── strategy_runs ───────────────────────────────────

class StrategyRun(Base):
    __tablename__ = "strategy_runs"

    id           = Column(Integer, primary_key=True, autoincrement=True)
    script_id    = Column(Integer, ForeignKey("scripts.id", ondelete="CASCADE"),
                          nullable=False)
    symbol       = Column(String(32), nullable=False)
    timeframe    = Column(String(8), nullable=False, default="1D")
    run_type     = Column(String(16), nullable=False, default="backtest")
    # "realtime" | "historical" | "backtest"

    status       = Column(String(16), nullable=False, default="pending")
    # "pending" | "running" | "completed" | "failed"

    bars_tested      = Column(Integer, nullable=True)
    execution_ms     = Column(Float, nullable=True)
    initial_capital  = Column(Float, nullable=False, default=10_000.0)
    fee_pct          = Column(Float, nullable=False, default=0.001)
    error_message    = Column(Text, nullable=True)

    started_at   = Column(DateTime(timezone=True), nullable=True)
    finished_at  = Column(DateTime(timezone=True), nullable=True)
    created_at   = Column(DateTime(timezone=True), nullable=False, default=_now)

    script         = relationship("Script", back_populates="runs")
    signals        = relationship("SignalHistory", back_populates="run",
                                  cascade="all, delete-orphan", lazy="select")
    backtest       = relationship("BacktestResult", back_populates="run",
                                  uselist=False, cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_strategy_runs_script_id", "script_id"),
        Index("ix_strategy_runs_symbol", "symbol"),
        Index("ix_strategy_runs_created_at", "created_at"),
    )


# ─────────────────────────── signal_history ──────────────────────────────────

class SignalHistory(Base):
    __tablename__ = "signal_history"

    id          = Column(BigInteger, primary_key=True, autoincrement=True)
    run_id      = Column(Integer, ForeignKey("strategy_runs.id", ondelete="CASCADE"),
                         nullable=False)
    bar_index   = Column(Integer, nullable=False)
    timestamp   = Column(DateTime(timezone=True), nullable=True)
    signal_type = Column(String(16), nullable=False)   # entry | exit | close
    label       = Column(String(64), nullable=True)
    price       = Column(Float, nullable=False)
    direction   = Column(String(8), nullable=True)     # buy | sell | neutral
    metadata_   = Column("metadata", JSON, nullable=True, default=dict)

    run         = relationship("StrategyRun", back_populates="signals")

    __table_args__ = (
        Index("ix_signal_history_run_id", "run_id"),
        Index("ix_signal_history_timestamp", "timestamp"),
    )


# ─────────────────────────── backtest_results ────────────────────────────────

class BacktestResult(Base):
    __tablename__ = "backtest_results"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    run_id           = Column(Integer, ForeignKey("strategy_runs.id", ondelete="CASCADE"),
                              nullable=False, unique=True)

    # Capital
    initial_capital  = Column(Float, nullable=False)
    final_capital    = Column(Float, nullable=True)
    net_profit_pct   = Column(Float, nullable=True)
    gross_profit_pct = Column(Float, nullable=True)
    gross_loss_pct   = Column(Float, nullable=True)

    # Trade stats
    total_trades          = Column(Integer, nullable=True, default=0)
    winning_trades        = Column(Integer, nullable=True, default=0)
    losing_trades         = Column(Integer, nullable=True, default=0)
    win_rate_pct          = Column(Float, nullable=True)
    avg_win_pct           = Column(Float, nullable=True)
    avg_loss_pct          = Column(Float, nullable=True)
    profit_factor         = Column(Float, nullable=True)
    max_consecutive_wins  = Column(Integer, nullable=True)
    max_consecutive_losses= Column(Integer, nullable=True)

    # Risk
    max_drawdown_pct = Column(Float, nullable=True)
    sharpe_ratio     = Column(Float, nullable=True)
    sortino_ratio    = Column(Float, nullable=True)
    calmar_ratio     = Column(Float, nullable=True)

    # JSON blobs
    trades_json       = Column(JSON, nullable=True)    # list[trade dicts]
    equity_curve_json = Column(JSON, nullable=True)    # list[float]

    created_at = Column(DateTime(timezone=True), nullable=False, default=_now)

    run = relationship("StrategyRun", back_populates="backtest")

    __table_args__ = (
        Index("ix_backtest_results_run_id", "run_id"),
    )
